---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-bitwarden"
  ADDON_SLUG: "bitwarden"
  ADDON_TARGET: "bitwarden"

  ADDON_ARMHF: "false"
  ADDON_I386: "false"

  ADDON_AARCH64_BASE: "hassioaddons/debian-base-aarch64:3.2.1"
  ADDON_AMD64_BASE: "hassioaddons/debian-base-amd64:3.2.1"
  ADDON_ARMV7_BASE: "hassioaddons/debian-base-armv7:3.2.1"


# Build overrides to supply a BITWARDEN_PLATFORM build argument
build:aarch64:
  script:
    - |
      docker build \
        --build-arg "BUILD_FROM=${FROM}" \
        --build-arg "BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ")" \
        --build-arg "BUILD_ARCH=${ADDON_ARCH}" \
        --build-arg "BUILD_REF=${CI_COMMIT_SHA}" \
        --build-arg "BUILD_VERSION=${CI_COMMIT_TAG:-${CI_COMMIT_SHA:0:7}}" \
        --build-arg "BITWARDEN_PLATFORM=linux/arm64/${ADDON_AARCH64_VARIANT}" \
        --cache-from "registry.gitlab.com/${CI_PROJECT_PATH}/${ADDON_ARCH}:cache" \
        --tag \
          "registry.gitlab.com/${CI_PROJECT_PATH}/${ADDON_ARCH}:${CI_COMMIT_SHA}" \
        "${ADDON_TARGET}"
    - |
      docker push \
        "registry.gitlab.com/${CI_PROJECT_PATH}/${ADDON_ARCH}:${CI_COMMIT_SHA}"
build:armv7:
  script:
    - |
      docker build \
        --build-arg "BUILD_FROM=${FROM}" \
        --build-arg "BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ")" \
        --build-arg "BUILD_ARCH=${ADDON_ARCH}" \
        --build-arg "BUILD_REF=${CI_COMMIT_SHA}" \
        --build-arg "BUILD_VERSION=${CI_COMMIT_TAG:-${CI_COMMIT_SHA:0:7}}" \
        --build-arg "BITWARDEN_PLATFORM=linux/arm/${ADDON_ARMV7_VARIANT}" \
        --cache-from "registry.gitlab.com/${CI_PROJECT_PATH}/${ADDON_ARCH}:cache" \
        --tag \
          "registry.gitlab.com/${CI_PROJECT_PATH}/${ADDON_ARCH}:${CI_COMMIT_SHA}" \
        "${ADDON_TARGET}"
    - |
      docker push \
        "registry.gitlab.com/${CI_PROJECT_PATH}/${ADDON_ARCH}:${CI_COMMIT_SHA}"
