---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-bitwarden"
  ADDON_SLUG: "bitwarden"
  ADDON_TARGET: "bitwarden"

  ADDON_ARMHF: "false"
  ADDON_I386: "false"

  ADDON_AARCH64_BASE: "hassioaddons/debian-base-aarch64:3.2.1"
  ADDON_AMD64_BASE: "hassioaddons/debian-base-amd64:3.2.1"
  ADDON_ARMV7_BASE: "hassioaddons/debian-base-armv7:3.2.1"
